### PR TITLE
feat(capture)!: add filter function opt for fields

### PR DESCRIPTION
**Pull request by bdarcus**
* citar-org-roam-template-fields: convert from cons to list

Close: #43

--------

Needs testing, and probably to add some default filter functions.

### CODE REVIEW

**Comment by bdarcus** [comment]
Need to get back to merging this!

**Comment by roshanshariff** [comment]
I'll look at this more deeply in a few days, but I wonder if most of this functionality should be in Citar? It could be useful to define some "virtual fields" there which are basically some bibliography fields, transformed by a filter function. You might want to use these in Citar templates as well. Perhaps citar-org-roam should just expose these Citar fields in Org-Roam templates?

**Comment by bdarcus** [comment]
Yeah, I was thinking something in citar itself might be better, but just not sure how that might work.

**Comment by bdarcus** [comment]
I'm going to close this in favor of the core package-only transform functions.

**Pull request closed without merging**
